FROM node:18-alpine

WORKDIR /var/www/html

# Copy package.json and package-lock.json
COPY package*.json ./

# Remove existing node_modules and package-lock.json if any
RUN rm -rf node_modules package-lock.json

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose Vite development server port
EXPOSE 5173

# Start Vite development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
